[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
truncate_to_repo = false
truncation_symbol = "…/"

[git_status]
format = '($ahead_behind )($conflicted$stashed )($deleted$renamed$staged )($modified$untracked )'
ahead      = "[⇡${count}](green)"
diverged   = "[⇡${ahead_count}⇣${behind_count}](yellow)"
behind     = "[⇣${count}](green)"
conflicted = "[=${count}](blue)"
stashed    = "[*${count}](blue)"
deleted    = "[✘${count}](red)"
renamed    = "[»${count}](yellow)"
staged     = "[+${count}](green)"
modified   = "[!${count}](yellow)"
untracked  = "[?${count}](yellow)"

