add_newline = false
format = """
[\
[ ](fg:0)\
$status\
$jobs\
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$git_metrics\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$crystal\
$nix_shell\
$conda\
$cmd_duration\
](bold fg:15 bg:0)\
[](fg:0)\
$line_break\
$character\
"""

##################################################
##  status                                      ##
##################################################

[status]
style = "bold fg:red bg:0"
format = " [$symbol$status]($style)"
disabled = false

[jobs]
style = "bold fg:blue bg:0"
symbol = ""
format = " [$symbol( $number)]($style)"

[username]
style_root = "bold fg:red bg:0"
style_user = "bold fg:yellow bg:0"
format = " [$user]($style) in"

[hostname]
style = "bold fg:dimmed green bg:0"
format = " [$hostname]($style) in"

[directory]
style = "bold fg:cyan bg:0"
format = " [$read_only]($read_only_style)[$path]($style) "
truncate_to_repo = false
truncation_symbol = "…/"

##################################################
##  vcs                                         ##
##################################################

[git_branch]
style = "bold fg:purple bg:0"
format = "on [$symbol$branch]($style) "

[git_commit]
style = "bold fg:green bg:0"
format = "[$hash$tag]($style) "

[git_state]
style = "bold fg:yellow bg:0"
format = "[$state($progress_current/$progress_total)]($style) "

[git_status]
format = '($ahead_behind )($conflicted$stashed )($deleted$renamed$staged )($modified$untracked )'
ahead      = "[↑${count}](bold fg:green bg:0)"
diverged   = "[↑${ahead_count}↓${behind_count}](bold fg:yellow bg:0)"
behind     = "[↓${count}](bold fg:green bg:0)"
conflicted = "[=${count}](bold fg:blue bg:0)"
stashed    = "[*${count}](bold fg:blue bg:0)"
deleted    = "[✘${count}](bold fg:red bg:0)"
renamed    = "[»${count}](bold fg:yellow bg:0)"
staged     = "[+${count}](bold fg:green bg:0)"
modified   = "[!${count}](bold fg:yellow bg:0)"
untracked  = "[?${count}](bold fg:yellow bg:0)"

[hg_branch]
style = "bold fg:purple bg:0"

##################################################
##  languages and ev tools                      ##
##################################################

[package]
style = "bold fg:208 bg:0"

[dart]
style = "bold fg:blue bg:0"

[golang]
style = "bold fg:cyan bg:0"

[cmake]
style = "bold fg:blue bg:0"

[lua]
style = "bold fg:blue bg:0"
symbol = " "

[java]
symbol = " "
style = "bold fg:red dimmed bg:0"

[kotlin]
style = "bold fg:#843eff dimmed bg:0"

[rust]
style = "bold fg:red bg:0"

[zig]
style = "bold fg:yellow bg:0"

[python]
symbol = " "
style = "bold fg:yellow bg:0"
format = "via [$symbol$pyenv_prefix($version )($virtualenv )]($style)"

##################################################
##  other                                       ##
##################################################

[cmd_duration]
style = "bold fg:yellow bg:0"
